#!/usr/bin/env bash
# Assemble PortSight.app from the SwiftPM executable, so the menu bar app runs
# as a proper agent (no Dock icon) without needing full Xcode.
set -euo pipefail

cd "$(dirname "$0")/.."

CONFIG="${1:-release}"
APP="PortSight.app"
CONTENTS="$APP/Contents"
EXECUTABLE="CablePro"   # SwiftPM product name (internal)

echo "▸ Building PortSight ($CONFIG)…"
swift build -c "$CONFIG" --product "$EXECUTABLE"

BIN_PATH="$(swift build -c "$CONFIG" --product "$EXECUTABLE" --show-bin-path)"

echo "▸ Assembling ${APP}…"
rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"

# Executable goes in Contents/MacOS. Its SwiftPM resource bundles must sit at
# the .app root: the generated `Bundle.module` accessor resolves them relative
# to `Bundle.main.bundleURL` (the .app itself), NOT Contents/Resources. Placing
# them under Resources makes the app fatalError at launch (bundle not found).
cp "$BIN_PATH/$EXECUTABLE" "$CONTENTS/MacOS/$EXECUTABLE"
find "$BIN_PATH" -maxdepth 1 -name '*.bundle' -exec cp -R {} "$APP/" \; 2>/dev/null || true

# App icon (generated by scripts/make-icon.sh).
ICON_LINE=""
if [[ -f "Resources/AppIcon.icns" ]]; then
    cp "Resources/AppIcon.icns" "$CONTENTS/Resources/AppIcon.icns"
    ICON_LINE="    <key>CFBundleIconFile</key>        <string>AppIcon</string>"
fi

cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>PortSight</string>
    <key>CFBundleDisplayName</key>     <string>PortSight</string>
    <key>CFBundleIdentifier</key>      <string>local.portsight.app</string>
    <key>CFBundleExecutable</key>      <string>$EXECUTABLE</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleShortVersionString</key> <string>0.1.1</string>
    <key>CFBundleVersion</key>         <string>2</string>
    <key>LSMinimumSystemVersion</key>  <string>14.0</string>
$ICON_LINE
    <!-- Menu-bar agent: no Dock icon, no app-switcher entry. -->
    <key>LSUIElement</key>             <true/>
</dict>
</plist>
PLIST

# Ad-hoc sign so macOS lets it run locally (personal use).
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 || \
    echo "  (codesign skipped — app will still run for personal use)"

echo "✓ Built $APP"
echo "  Run it with:  open $APP"
echo "  Look for the PortSight icon in your menu bar."
